stages:
- name: Deploy some workloads
  steps:
  - runScriptConfig:
      image: python:latest
      shellScript: echo "hello"
timeout: 30
branch:
  include:
  - master
  - feature/*
  exclude:
  - dev
notification: {}
