name: build, test and deploy test environment on pr

on:
  pull_request:
    branches:
    - main

  push:
    branches:
    - build_test_deploy

jobs:
  
  build_and_test:
    runs-on: ubuntu-20.04

    steps:

      - uses: actions/checkout@v2

      - name: Set image tag
        run: |
          SHORT_SHA=$(git describe --always)
          echo "internetee/auction:RC_$SHORT_SHA" > TAG

      - name: Set ENV for codeclimate (push)
        if: github.event_name == 'push'
        run: |
          echo "$GITHUB_REF" > GIT_BRANCH
          echo "$GITHUB_SHA" > GIT_COMMIT_SHA

      - name: Set ENV for codeclimate (pull request)
        if: github.event_name == 'pull_request'
        run: |
          echo "$GITHUB_HEAD_REF" > GIT_BRANCH
          echo "$(git rev-parse origin/$GITHUB_HEAD_REF)" > GIT_COMMIT_SHA

      - name: Build image
        run: |
          docker build -t $(cat TAG) .
          docker images